# Below are urls and api endpoints
# for obtaining all raw data
# We will organize by county, state
# and national downloads
# And then, within each, we will
# organize by url and api calls
# Finally, we will include key/val pairs
# for component type (i.e. haz, exp, vuln)
# and other identifiers (i.e. social, physical)
# that are useful for organizational logic

# There are different rules for downloading
# data from API or URL endpoints, since the former
# require some parameters whereas the latter
# point straight to a file to download
# We will first have keys
# for api/url 
# Then we will structure by keys
# for the data type (i.e. haz/exp)
# that will define file directories and paths
# These all need to be nested within 
# the following keys
# county, state, national, external
# we want to download data from
# largest to smallest scale (i.e. national, state, county)
# because of their set-type relationships (i.e. many counties in one state
# and many states in one nation)
download:
  FIPS:
    api:
      exp: 
        # NSI has an API endpoint
        # We call it county by county
        nsi: "https://nsi.sec.usace.army.mil/nsiapi/structures?fips={FIPS}"
        assess: "https://phl.carto.com/api/v2/sql?filename=opa_properties_public&format=geojson&skipfields=cartodb_id&q=SELECT+*+FROM+opa_properties_public"
        bldfp: "https://opendata.arcgis.com/api/v3/datasets/ab9e89e1273f445bb265846c90b38a96_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1"
        parcel: "https://opendata.arcgis.com/api/v3/datasets/84baed491de44f539889f2af178ad85c_0/downloads/data?format=geojson&spatialRefId=4326&where=1%3D1"
    url:
        # We use the national flood hazard layer for flood zones
        # These URLs currently are not in a structured format so I manually input this
        # after searching on the FEMA map services center
        pol:
          nfhl: "https://hazards.fema.gov/nfhlv2/output/County/420757_20230701.zip"
        
  STATEABBR:
    url:
      ref:
        # replace STATE_FIPS with st_fips in the download rule
        # We have a helper function in a util/ directory that replaces
        # Tract, block group, and block geospatial boundaries are available at state level
        tract: "https://www2.census.gov/geo/tiger/TIGER2022/TRACT/tl_2022_{STATEFIPS}_tract.zip"
        bg: "https://www2.census.gov/geo/tiger/TIGER2022/BG/tl_2022_{STATEFIPS}_bg.zip"
        block: "https://www2.census.gov/geo/tiger/TIGER2022/TABBLOCK20/tl_2022_{STATEFIPS}_tabblock20.zip"
  NATION:
    url:
      vuln:
        social:
          # CEJST and CDC SVI
          cejst: "https://dblew8dgr6ajz.cloudfront.net/data-versions/2.0/data/score/downloadable/2.0-communities.csv"
          svi: "https://svi.cdc.gov/Documents/Data/2020/csv/states/SVI_2020_US.csv"
      ref:
        # County and zip code tabulation area spatial data available for the whole country
        county: "https://www2.census.gov/geo/tiger/TIGER2022/COUNTY/tl_2022_us_county.zip"
        zcta: "https://www2.census.gov/geo/tiger/TIGER2022/ZCTA520/tl_2022_us_zcta520.zip"
# We need to keep track of the format different api data is returned in
# to write it out
api_ext:
  nsi: ".json"
  assess: ".geojson"
  bldfp: ".geojson"
  parcel: ".geojson"

# We need to keep track of which wildcards are used in urls
url_wildcards: ["{FIPS}", "{STATEABBR}", "{STATEFIPS}", "{NATION}"]

# Keep track of NSI CRS
nsi_crs: "EPSG:4326"

# Dictionary of reference filenames to 
# what we want them to say
ref_names:
  tract: "tract"
  tabblock20: "block"
  bg: "bg"
  county: "county"
  zcta520: "zcta"

# Dictionary of ref names to their
# id column
ref_id_names:
  tract: "GEOID"
  block: "GEOID20"
  bg: "GEOID"
  county: "GEOID"
  zcta: "GEOID20"

# Uncertainty for structure values
coef_var: .2

# Dictionary of foundation types 
ffe_dict:
  S: [0, .5, 1.5]
  C: [0, 1.5, 4]
  B: [0, 1.5, 4]

## Convergence testing
# Number of seeds 
seeds: 20
# SOWs to test 
sow_test: [10, 100, 500, 1000]

## Ensemble experiments
# For all flood scenarios
base_configs:
  no_adj:
    coef_var: .2
    n_sow: 500
    id_col: 'fd_id'
    base_adj: False
    depth_min: .01

model_configs:
  phil: 
    struct_list: ['val_struct', 'ffe']
    base_data: 'phil'
    supp_data: []
    val_adj: False
    label: 'Philly Inventory'
  nsi_ddfs:
    struct_list: []
    base_data: 'nsi'
    supp_data: []
    val_adj: False
    label: 'NSI Loc., DDF Unc. Only'
  nsi_unsafe: 
    struct_list: ['val_struct', 'ffe', 'num_story', 'found_type']
    base_data: 'nsi'
    supp_data: []
    val_adj: False
    label: 'NSI Loc., NSI Struct All Unc.'
  nsi_phil:
    struct_list: ['val_struct', 'ffe', 'num_story', 'found_type']
    base_data: 'nsi'
    supp_data: ['phil_stories_stats', 'phil_found_stats']
    val_adj: False
    label: 'NSI Loc., Philly Struct All Unc.'
  phil_unsafe:
    struct_list: ['val_struct', 'ffe', 'num_story', 'found_type']
    base_data: 'phil'
    supp_data: []
    val_adj: False
    label: 'Philly Loc., Philly Struct All Unc.'
  nsi_allphil:
    struct_list: ['val_struct', 'ffe', 'num_story', 'found_type']
    base_data: 'nsi'
    supp_data: ['phil_stories_stats', 'phil_found_stats']
    val_adj: True
    label: 'NSI Loc., Philly Struct All Unc w Val Update.'

# Overarching inventory adjustments
# for main and sensitivity
# runs for all the experiments
# We update 
# whether to look at assigned or all res1
# min depth thresholds
# whether to truncate structure values for 3s buildings
sample_configs:
  main:
    trunc_val: False
    d_min: .01
    res1_bool: True
  sa1:
    trunc_val: True
    d_min: .01
    res1_bool: True
  sa2:
    trunc_val: False
    d_min: .01
    res1_bool: False
  sa3:
    trunc_val: False
    d_min: .001
    res1_bool: True
  sa4:
    trunc_val: False
    d_min: .1
    res1_bool: True
    
# Number of SOWs
# for main scenario ensemble
sows: 1000

# Depth grid id for 
# main scenario
# Could add to list if desired
main_dg: ['009']  

## Hazard model configurations
# For this case study, we have 50 representations
# of the same event. These files have the
# same filenaming convention
haz_filename: "Irene/Irene_final/ENS_{ens_num}.txt"
# Number of ensemble members
haz_nens: 50
# Number of columns for each depth grid
haz_ncols: 1499
# Num rows for each depth grid
haz_nrows: 2106
# Lower left x coordinate
haz_xll: -75.2785647388855
# Lower left y coordinate
haz_yll: 39.8560647920825
# Cell resolution
haz_res: 9.2592593e-05
# NODATA values
haz_nodata: -9999
# CRS
haz_crs: 4269